# Generated by Django 5.0.4 on 2024-05-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi3smart', '0010_remove_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imagee',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
