# Generated by Django 5.0.4 on 2024-05-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi3smart', '0018_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
